[package]
name = "minect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "minect"

[dependencies]
encoding_rs = "0.8"
flate2 = "1"
fs3 = "0.5"
hematite-nbt = { version = "0.5" }
log = "0.4"
notify = "5"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = [
  "fs",
  "io-util",
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tokio-stream = { version = "0.1" }

[dev-dependencies]
serial_test = "0.10"
strum = { version = "0.24", features = ["derive"] }

[build-dependencies]
walkdir = "2"
