[package]
name = "minecraft-command-injection"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mc_inject"

[dependencies]
hematite-nbt = { version = "0.5" }
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
notify = "4.0"
tokio = { version = "1.8", features = ["fs", "io-util", "rt-multi-thread", "macros", "sync", "time"] }

[dev-dependencies]
strum = { version = "0.21", features = ["derive"] }
