[package]
name = "minecraft-command-injection"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mc_inject"

[dependencies]
hematite-nbt = { version = "0.5", features = ["preserve_order"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
strum = { version = "0.21", features = ["derive"] }
